### ISSUE TITLE
Peds exept the basic ones doesent appear  in the Character Screen

### ISSUE THREAD

**Issue by JeyCraft** [renzuzu/renzu_multicharacter#47]
Hew we have some issues when player Choose PEDS Exept the normal multiplayer character wont appear right in the Menu. So Animals & Normal Peds like NoosePed arent displayed right in the Menu. ):

**Comment by renzuzu** [comment]
did you solve this?

**Comment by JeyCraft** [comment]
it was solved first, already createt characters working fine but for new Characters they now invisible when create. -.-

**Comment by renzuzu** [comment]
it should not be invisible if your using correct skin 
or if your using latest version, there shouldd be a warning message and setting invisible peds (no skin) to default skins

**Comment by JeyCraft** [comment]
im usining illienium appearance newst version, if i start multicharacter it says theres no supportet skin resource... I just backgraded now on the version earlier so it works again.

**Comment by renzuzu** [comment]
i am using illenium with some server i manage,

can you make a clip of it if issue still exist?
